export const sample_foods = [
    {
        id:'1',
        name:'Pizza Pepperoni',
        cookTime: '10-20',
        price: 120,
        favorite: true,
        origins: ['Italy'],
        stars: 4.5,
        imageUrl:'food-1.jpg',
        tags:['FastFood', 'Pizza', 'Lunch'],

    },
    {
        id:'2',
        name:'MeatBall',
        cookTime: '20-30',
        price: 320,
        favorite: false,
        origins: ['Persia','Middle East','China'],
        stars: 5,
        imageUrl:'food-2.jpg',
        tags:['SlowFood', 'Lunch'],
    },
    {
        id:'3',
        name:'Hamburger',
        cookTime: '10-15',
        price: 30,
        favorite: false,
        origins: ['Germany','US'],
        stars: 4.0,
        imageUrl:'food-3.jpg',
        tags:['FastFood', 'Hamburger'],
    },
    {
        id:'4',
        name:'Fried Potatoes',
        cookTime: '15-20',
        price: 90,
        favorite: true,
        origins: ['Belgium','France'],
        stars: 3.5,
        imageUrl:'food-4.jpg',
        tags:['FastFood', 'Fry'],
    },
    {
        id:'5',
        name:'Chicken Soup',
        cookTime: '35-40',
        price: 290,
        favorite: false,
        origins: ['India','Asia'],
        stars: 3.5,
        imageUrl:'food-5.jpg',
        tags:['SlowFood', 'Soup'],
    },
    {
        id:'6',
        name:'Veg Pizza',
        cookTime: '25-30',
        price: 99,
        favorite: false,
        origins: ['Italy'],
        stars: 4.5,
        imageUrl:'food-6.jpg',
        tags:['FastFood', 'Pizza','Lunch'],
    }
];
export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
  ];
  export const sample_users = [
    {
      id: 1,
      name: 'Vidit Dubey',
      email: 'vidit@gmail.com',
      password: '12345',
      address: 'Lucknow',
      isAdmin: true,
    },
    {
      id: 2,
      name: 'Shivvishal Dubey',
      email: 'shiv@gmail.com',
      password: '12345',
      address: 'Jhansi',
      isAdmin: false,
    },
  ];